#! /bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: libcset <executable_path> <glibc_version>"
    echo "Available versions are:"
    ls /opt/libcbench/glibc
    echo "You can also set glibc_version to 0 to use the system's glibc."
    exit 0
fi

if [ "$2" == "0" ]; then
    patchelf --set-interpreter /usr/lib/x86_64-linux-gnu/ld-linux-x86-64.so.2 --set-rpath /usr/lib/x86_64-linux-gnu "${1}"
else
    if [ ! -d "/opt/libcbench/glibc/${2}" ]; then
        echo "Error: glibc version ${2} is not installed."
        exit 1
    fi
    patchelf --set-interpreter /opt/libcbench/glibc/${2}/lib/ld-linux-x86-64.so.2 --set-rpath /opt/libcbench/glibc/${2}/lib "${1}"
fi
